[project]
name = "email-to-slack-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-storage>=2.14.0",
    "slack-sdk>=3.27.0",
]
